name       : qastools
version    : 0.22.0
release    : 5
source     :
    - https://gitlab.com/sebholt/qastools/-/archive/v0.22.0/qastools-v0.22.0.tar.gz : 58a5b06a848115a56ca63b53b218e8f595342efd312cd91a878712641a5a913c
license    : MIT
component  : multimedia.audio
summary    : QasTools is a collection of Qt-based mixer and setup tools for the Linux sound system ALSA.
description: |
    QasTools is a collection of Qt-based mixer and setup tools for the Linux sound system ALSA.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
