name       : qastools
version    : 0.23.0
release    : 6
source     :
    - https://gitlab.com/sebholt/qastools/-/archive/v0.23.0/qastools-v0.23.0.tar.gz : 44470eb5e988aaf9cacb3bb7f40ccad9581a7b1e23ef2ceb98d808c661b64ee3
homepage   : https://gitlab.com/sebholt/qastools
license    : MIT
component  : multimedia.audio
summary    : Desktop toolset for the Linux sound system ALSA
description: |
    QasTools is a collection of Qt-based mixer and setup tools for the Linux sound system ALSA.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(alsa)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
