name       : qastools
version    : 0.21.0
release    : 2
source     :
    - https://sourceforge.net/projects/qastools/files/0.21.0/qastools_0.21.0.tar.gz/download : 73cf5568ab4c49c72dcb5f09f5dfad55e7e0a4c90c1a4794718e899ccddf5207
license    : GPL-3.0
component  : multimedia.audio
summary    : QasTools is a collection of Qt-based mixer and setup tools for the Linux
    sound system ALSA.
description: |
    QasTools is a collection of Qt-based mixer and setup tools for the Linux sound system ALSA.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
